# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{ secrets.REPO_READ_ONLY_TOKEN }}"

updates:
  - package-ecosystem: github-actions
    directory: / # scans workflows + actions
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Amsterdam
    labels: [dependencies, github-actions]
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 5
    groups:
      actions:

  - package-ecosystem: pip
    directory: / # Scans pyproject.toml + poetry.lock
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Amsterdam
    labels: [dependencies, python]
    commit-message:
      prefix: "deps(python)"
      include: scope
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-major-days: 14
    groups:
      python-patch-minor:
        update-types: [patch, minor]

  - package-ecosystem: docker
    directories: ["/", "/docker"]
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Amsterdam
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 5
    groups:
      docker-patch-minor:
        update-types: [patch, minor]

  - package-ecosystem: npm
    directory: /
    registries: [npm-github]
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    labels: [dependencies, javascript]
    commit-message:
      prefix: "deps(npm)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-major-days: 14
    groups:
      npm-patch-minor:
        update-types: [patch, minor]
